name: Run c_binder_mojo unit tests
on:
  schedule:
    - cron: '1 6 * * 5'
  workflow_dispatch: #allows you to trigger manually
  push:
    branches:
      - fix/generalize-tests

jobs:
  run_tests:
    runs-on: ${{ matrix.runner.RUNNER_NAME }}
    strategy:
      max-parallel: 2
      matrix:
        runner:
          - RUNNER_NAME: ubuntu-24.04-arm
            PLATFORM: arm64
          - RUNNER_NAME: ubuntu-latest
            PLATFORM: x86_64
        build_type: [cpu]
    steps:
    - name: Copy This Repository Contents
      uses: actions/checkout@v2

    - name: Fix workspace permissions
      run: |
        sudo chown -R 1000:1000 .

    - name: Pull docker image and run tests
      run: |
        export DOCKER_BUILDKIT=1
        export COMPOSE_PROFILES=${BUILD_TYPE}_${PLATFORM}
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin

        if docker compose pull; then
            echo "Docker Compose pull succeeded."
        else
            echo "Docker Compose pull failed."
        fi
        
        docker compose run --rm c_binder_mojo_${COMPOSE_PROFILES} bash -l -c "pixi run test_all"
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BUILD_TYPE: ${{ matrix.build_type }}
        PLATFORM: ${{ matrix.runner.PLATFORM }}