# version: "3.8"

x-c_binder_mojo_base: &c_binder_mojo_base
  working_dir: /home/mojo_user/c_binder_mojo
  logging:
    driver: json-file
    options:
      max-size: 50m
  stdin_open: true
  tty: true
  shm_size: 16000000000
  ports:
    - "5900:5900"
  volumes:
    - .:/home/mojo_user/c_binder_mojo/
    - ~/.ssh:/home/mojo_user/.ssh:rw
    - c_binder_mojo_vscode_data_cache:/home/mojo_user/.vscode-server/data/User/globalStorage:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  environment:
    C_BINDING_MOJO_TEST_MUJOCO: /home/mojo_user/c_binder_mojo/mujoco_mojo/mujoco
    PIXI_ENVIRONMENT_NAME: ${PIXI_ENVIRONMENT_NAME:-default}
    DISPLAY: host.docker.internal:0

volumes:
  c_binder_mojo_vscode_data_cache:
      external: false

services:
  c_binder_mojo_build_x86_64:
    build:
      dockerfile: c_binder_mojo.Dockerfile
      context: .
      args:
      - BASE_IMAGE=ubuntu:22.04
      cache_from:
      - josiahls/c_binder_mojo-x86_64:${VERSION:-latest}
    image: josiahls/c_binder_mojo-x86_64:${VERSION:-latest}
    profiles: ["build_x86_64"]
    platform: linux/amd64

  c_binder_mojo_build_arm64:
    build:
      dockerfile: c_binder_mojo.Dockerfile
      context: .
      args:
      - BASE_IMAGE=arm64v8/ubuntu:22.04
      cache_from:
      - josiahls/c_binder_mojo-arm64:${VERSION:-latest}
    image: josiahls/c_binder_mojo-arm64:${VERSION:-latest}
    profiles: ["build_arm64"]
    platform: linux/arm64

  c_binder_mojo_cpu_arm64: &c_binder_mojo_cpu_arm64
    <<: *c_binder_mojo_base
    profiles: ["cpu_arm64"]
    restart: unless-stopped
    platform: linux/arm64
    image: josiahls/c_binder_mojo-arm64:${VERSION:-latest}

  c_binder_mojo_gpu_arm64: &c_binder_mojo_gpu_arm64
    <<: *c_binder_mojo_cpu_arm64
    profiles: ["gpu_arm64"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  c_binder_mojo_cpu_x86_64: &c_binder_mojo_cpu_x86_64
    <<: *c_binder_mojo_base
    profiles: ["cpu_x86_64"]
    restart: unless-stopped
    platform: linux/amd64
    image: josiahls/c_binder_mojo-x86_64:${VERSION:-latest}

  c_binder_mojo_gpu_x86_64: &c_binder_mojo_gpu_x86_64
    <<: *c_binder_mojo_cpu_x86_64
    profiles: ["gpu_x86_64"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  

