[project]
authors = ["josiahls <jklaivins@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly", 
    "https://conda.modular.com/max", 
    "https://repo.prefix.dev/modular-community", 
    "conda-forge"
]
name = "c_binder_mojo"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
max = ">=25.5.0.dev2025062005,<25.5.0.dev2025070105"

[tasks]
################## Test C Project Configuration ##################
init_test_c_project = { cmd = [
    "cd", "tests/test_c_project", "&&",
    "mkdir", "-p", "build", "&&",
    "cd", "build", "&&",
    "cmake", ".."
], outputs = ["tests/test_c_project/build"]}

build_test_c_project = { cmd = [
        "cd", "tests/test_c_project/build", "&&",
        "make",
    ], depends-on = [
        "init_test_c_project"
    ],  outputs = [
        "tests/test_c_project/build/libtest_c_project.so" 
]}

################## Firehose Setup ##################
clone_firehose = { cmd = [
    "bash", "-c", 
    "if [ ! -d firehose ]; then git clone https://github.com/josiahls/firehose.git; else echo 'Firehose directory already exists.'; fi"
]}

configure = { cmd = [
    "git", "submodule", "update", "--remote",
], depends-on = [ "clone_firehose" ] }



################## Core API ##################

package = "mojo package -I firehose c_binder_mojo"
generate_bindings = "mojo run -I . -I firehose cli.mojo"


################## Testing ##################

# Shell commands
shell = "cd . && pixi shell"
s = "pixi run shell"
p = "pixi run package"
bt = "pixi run build_test"


# c_binder_mojo Development tools
## Just format the c_binder_mojo src directory, not the tests.
format = "mojo format c_binder_mojo"
f = "pixi run format"

## Common testing tasks
test_all = "mojo test -I . -I tests -I firehose tests"



## Combined workflows
build_test = "pixi run format && pixi run test_all"


