[project]
authors = ["Josiah Laivins <jklaivins@gmail.com>"]
channels = [
    "https://conda.modular.com/max-nightly", 
    "https://repo.prefix.dev/modular-community", 
    "conda-forge"
]
name = "c_binder_mojo"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"
license = "Apache-2.0"
license-file = "LICENSE"
homepage = "https://github.com/josiahls/c_binder_mojo"
repository = "https://github.com/josiahls/c_binder_mojo"

[dependencies]
mojo = ">=25.6.0.dev2025080116"
pre-commit = ">=4.2.0,<5"

[activation.env]
LD_LIBRARY_PATH="$PIXI_PROJECT_ROOT/tests/test_c_project/build:$LD_LIBRARY_PATH"
MODULAR_MOJO_MAX_IMPORT_PATH="$PIXI_PROJECT_ROOT/modular/bazel-bin"

[tasks]
######################## Test C Project Configuration #########################
init_test_c_project = { cmd = [
    "cd", "tests/test_c_project", "&&",
    "mkdir", "-p", "build", "&&",
    "cd", "build", "&&",
    "cmake", ".."
], outputs = ["tests/test_c_project/build"]}

build_test_c_project = { cmd = [
    "cd", "tests/test_c_project/build", "&&",
    "make",
], depends-on = [
    "init_test_c_project"
]}


########################### Firehose Configuration ############################
clone_firehose = { cmd = [
    "bash", "-c", 
    "if [ ! -d firehose ]; then git clone https://github.com/josiahls/firehose.git; else echo 'Firehose directory already exists.'; fi"
]}

########################### EmberJson Configuration ############################
clone_emberjson = { cmd = [
    "bash", "-c", 
    "if [ ! -d EmberJson ]; then git clone https://github.com/josiahls/EmberJson.git; else echo 'EmberJson directory already exists.'; fi"
]}

########################## Mojo Standard Library ##############################
clone_stdlib = { cmd = [
    "bash", "-c", 
    "if [ ! -d modular ]; then git clone https://github.com/max-lang/modular.git; else echo 'Modular directory already exists.'; fi"
]}

update_stdlib = { cmd = [
    "cd", "modular", "&&",
    "git", "fetch", "origin", "&&",
    "git", "checkout", "josiahls/add-ulong-c-ffi", "&&",
    "git", "pull", "origin", "josiahls/add-ulong-c-ffi", "&&",
    "bazelw", "build", "//mojo/stdlib/stdlib"
], depends-on = [ "clone_stdlib" ]}

clean_update_stdlib = { cmd = [
    "cd", "modular", "&&",
    "git", "fetch", "origin", "&&",
    "git", "checkout", "josiahls/add-ulong-c-ffi", "&&",
    "git", "reset", "--hard", "origin/josiahls/add-ulong-c-ffi", "&&",
    "bazelw", "build", "//mojo/stdlib/..."
], depends-on = [ "clone_stdlib" ]}

######################### Pre-commit Configuration ##########################
install_pre_commit_hooks = { cmd = [
    "pre-commit", "install"
], outputs = [".git/hooks/pre-commit"]}

######################### Core API ############################################
configure = { cmd = [
    "echo", "configuring"
], depends-on = [ "clone_firehose", "clone_emberjson", "build_test_c_project", "install_pre_commit_hooks", "update_stdlib" ] }

generate_bindings = { cmd = [
    "mojo", "run", "-I", ".", "-I", "firehose", "-I", "EmberJson", "cli.mojo"
], depends-on = [ "configure" ]}

package = { cmd = [
    "mojo", "package", "-I", "firehose", "-I", "EmberJson", "c_binder_mojo"
], depends-on = [ "configure" ]}

format = { cmd = [
    "mojo", "format", "c_binder_mojo"
]}


######################### Testing Configuration ###############################
# Build the c bindings.
build_test_c_project_bindings = { cmd = [
    "pixi", "run", "generate_bindings", 
    "tests/test_c_project/include/simple_type_defs.h",
    "tests/test_c_project/build",
    "tests/test_c_project/build/libtest_c_project.so",
], depends-on = [ "configure" ]}


######################### Testing #############################################

test_all = { cmd = [
    "bash", "tests/run_tests.sh"
], depends-on = [ "build_test_c_project_bindings" ]}

test_all_stdlib = { cmd = [
    "bash", "tests/run_tests.sh"
], depends-on = [ "update_stdlib", "build_test_c_project_bindings" ]}

test_all_stdlib_clean = { cmd = [
    "bash", "tests/run_tests.sh"
], depends-on = [ "clean_update_stdlib", "build_test_c_project_bindings" ]}
