# Native Mojo Modules
# Third Party Mojo Modules
# First Party Modules


trait NodeAstLike(Moveable,Stringable): 
    alias __name__:String
    
    fn parent_idx(self) -> Int: ...
    fn current_idx(self) -> Int: ...
    fn set_current_idx(mut self, value:Int): ...
    fn children_idxs(mut self) -> ArcPointer[List[Int]]: ...

    fn display_name(self) -> String: ...
    fn token_bundles(self) -> TokenBundles: ...
    fn should_children_inline(self) -> Bool: ...
