name: Run c_binder_mojo unit tests
on:
  schedule:
    - cron: '1 6 * * 5'
  workflow_dispatch: #allows you to trigger manually
  push:
    branches:
      - fix/generalize-tests

jobs:
  build:
    runs-on: ${{ matrix.runner.RUNNER_NAME }}
    image: "josiahls/c_binder_mojo-${{ matrix.build_type }}-${{ matrix.runner.PLATFORM }}:latest"
    strategy:
      max-parallel: 2
      matrix:
        runner:
          - RUNNER_NAME: ubuntu-24.04-arm
            PLATFORM: arm64
          - RUNNER_NAME: ubuntu-latest
            PLATFORM: x86_64
        build_type: [cpu]
    steps:
    - name: Copy This Repository Contents
      uses: actions/checkout@v2

    - name: build, tag, and push image
      run: |
        echo "Hello, world!"
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        BUILD_TYPE: ${{ matrix.build_type }}
        PLATFORM: ${{ matrix.runner.PLATFORM }}
